FROM v4tech/latex:latest
MAINTAINER Stewart V. Wright <stewart@vifortech.com>

# Install R
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
            R-base && \
    rm -rf /var/lib/apt/lists/*
